module.exports = {
  testEnvironment: 'jsdom',
  setupFilesAfterEnv: ['<rootDir>/src/setupTests.js'],
  moduleNameMapper: {
    '\\.(css|less|scss|sass)$': 'identity-obj-proxy',
    '\\.(svg|png|jpg|jpeg|gif|webp)$': '<rootDir>/src/__mocks__/fileMock.js',
  },
  transform: {
    '^.+\\.(js|jsx)$': 'babel-jest',
  },
  transformIgnorePatterns: [
    'node_modules/(?!(gbimage-bridge|swiper|@react-icons|@sistent)/)',
  ],
  testMatch: ['<rootDir>/src/**/*.(test|spec).js'],
  testPathIgnorePatterns: [
    '<rootDir>/src/utils/',
    '<rootDir>/src/components/',
    '<rootDir>/src/sections/Blog/',
    '<rootDir>/src/sections/Careers/',
    '<rootDir>/src/sections/Community/',
    '<rootDir>/src/sections/Company/About/',
    '<rootDir>/src/sections/Company/Brand/',
    '<rootDir>/src/sections/Company/Contact/',
    '<rootDir>/src/sections/Company/Layer5-statement/',
    '<rootDir>/src/sections/Company/News-grid/',
    '<rootDir>/src/sections/Company/News-single/index.test.js',
    '<rootDir>/src/sections/Company/News/',
    '<rootDir>/src/sections/Company/Stewards-of-industry/',
    '<rootDir>/src/sections/Company/WhoWeAre/',
    '<rootDir>/src/sections/Counters/',
    '<rootDir>/src/sections/DeployServiceMesh/',
    '<rootDir>/src/sections/DoYouNeedService/',
    '<rootDir>/src/sections/General/',
    '<rootDir>/src/sections/Home/',
    '<rootDir>/src/sections/Kanvas/',
    '<rootDir>/src/sections/Learn/',
    '<rootDir>/src/sections/Meshery/',
    '<rootDir>/src/sections/Projects/',
    '<rootDir>/src/sections/Resources/',
    '<rootDir>/src/sections/what-is-service-mesh/',
  ],
  globals: {
    'NODE_ENV': 'test',
  },
  collectCoverageFrom: [
    'src/**/*.{js,jsx}',
    '!src/**/*.d.ts',
    '!src/**/*.test.js',
    '!src/**/*.spec.js',
    '!src/utils/**',
  ],
};
