import styled from "styled-components";

const MeshSectionWrapper = styled.section`
  margin: 0rem 0rem 2.25rem 0rem;
  position: relative;
  overflow: hidden;
  .title { 
    text-transform: uppercase;
    color: #A0AAAA;
  }
  .big-title {
    color: ${props => props.theme.text};
  }
  .side-text {
    font-size: 1.45rem;
    font-weight: 600;
    line-height: 2rem;
    color: ${props => props.theme.text};
    margin: 50px 0 24px 0;
    span {
           font-weight: 300;
            /* color: ${props => props.theme.keppelColor}; */

        }
   }
   .side{
       vertical-align: center;
      
   }
   .mesh-image{
        width: 100%; 
   }
   .icon{
       padding: 0px;
       margin: 3px;
       cursor: pointer;
       vertical-align: middle;
       }
   
   .description{
       margin-bottom: 24px;
       font-style: normal;
       font-weight: 300;
       font-size: 1rem;
       line-height: 27px;
   }
   .strikethrough {
    text-decoration: line-through;
    font-weight: 400;
   }
   a:hover {
    color: ${props => props.theme.text}
   }

  @media only screen and (max-width: 780px) {
    .mesh-image{
        display: block;
        margin-left: auto;
        margin-right: auto;
    }
    .section-title{
        margin-bottom: 1rem;
        /* padding-bottom: 1.5rem; */
        
    }
    .side-text{
        padding-top: 0rem;
        font-weight: 500;
        font-size: 1.25rem;
        text-align: center;
        line-height: 2rem;
        margin-top: 1rem;
        span {
           font-weight: 600;
            color: ${props => props.theme.keppelColor};
        }
    }
    .big-title{
        margin: 0;
        padding: 0;
    }

    .description{
        text-align: center;
        padding-left: 20px;
        padding-right: 20px;
        font-weight: 300;
        margin: 0;
    }
    .backBtn{
        text-align: center;
    }

  }
  @media only screen and (max-width: 568px) {
    padding: 60px 0 40px 0;
      .section-title{
          margin: 0;
          padding: 0;
      }
     .section-title,
     .content-wrap{
        text-align: center;
    }
    .mesh-image{
        display: block;
        margin-left: auto;
        margin-right: auto;
        width: 80%;
        margin-top: 1rem;
        margin-bottom: 1rem;
    }
    .side-text{
            font-size: 1.25rem;
            font-weight: 400;
            text-align: center;
            line-height: 21px;
            span {
                font-weight: 400;
            }
            
    }
    .big-title{
        margin: 0;
        padding: 0;
    }
    
    .description{
        text-align: center;
        padding-left: 20px;
        padding-right: 20px;
        font-weight: 300;
        margin: 0;
    }

  @media only screen and (max-width: 480px) {
    padding: 40px 20px 60px 20px;
    .section-title{
          margin-bottom: 1rem;
          padding: 0;
      }

    .description{
        margin: 0px;
    }
  }

  }

/***************************************************
 * Generated by SVG Artista on 1/31/2021, 3:47:32 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/
.meshmap {
svg .svg-elem-1{stroke-dashoffset:168.8795166015625px;stroke-dasharray:168.8795166015625px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 2.5s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 0s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 2.5s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 0s}svg.active .svg-elem-1{stroke-dashoffset:0;fill:rgb(0,0,0)}svg .svg-elem-2{stroke-dashoffset:168.8795166015625px;stroke-dasharray:168.8795166015625px;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 2.6s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 0.09s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 2.6s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 0.09s}svg.active .svg-elem-2{stroke-dashoffset:0}svg .svg-elem-3{stroke-dashoffset:173.59739685058594px;stroke-dasharray:173.59739685058594px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 2.7s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 0.18s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 2.7s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 0.18s}svg.active .svg-elem-3{stroke-dashoffset:0;fill:rgb(0,179,159)}svg .svg-elem-4{stroke-dashoffset:173.56723022460938px;stroke-dasharray:173.56723022460938px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 2.8s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 0.27s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 2.8s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 0.27s}svg.active .svg-elem-4{stroke-dashoffset:0;fill:rgb(0,179,159)}svg .svg-elem-5{stroke-dashoffset:83.45301055908203px;stroke-dasharray:83.45301055908203px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 2.9s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 0.36s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 2.9s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 0.36s}svg.active .svg-elem-5{stroke-dashoffset:0;fill:rgb(0,0,0)}svg .svg-elem-6{stroke-dashoffset:83.45301055908203px;stroke-dasharray:83.45301055908203px;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 3s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 0.44999999999999996s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 3s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 0.44999999999999996s}svg.active .svg-elem-6{stroke-dashoffset:0}svg .svg-elem-7{stroke-dashoffset:173.4873046875px;stroke-dasharray:173.4873046875px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 3.1s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 0.54s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 3.1s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 0.54s}svg.active .svg-elem-7{stroke-dashoffset:0;fill:rgb(0,179,159)}svg .svg-elem-8{stroke-dashoffset:173.54556274414062px;stroke-dasharray:173.54556274414062px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 3.2s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 0.63s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 3.2s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 0.63s}svg.active .svg-elem-8{stroke-dashoffset:0;fill:rgb(0,179,159)}svg .svg-elem-9{stroke-dashoffset:173.59738159179688px;stroke-dasharray:173.59738159179688px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 3.3s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 0.72s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 3.3s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 0.72s}svg.active .svg-elem-9{stroke-dashoffset:0;fill:rgb(0,179,159)}svg .svg-elem-10{stroke-dashoffset:100.71990203857422px;stroke-dasharray:100.71990203857422px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 3.4s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 0.8099999999999999s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 3.4s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 0.8099999999999999s}svg.active .svg-elem-10{stroke-dashoffset:0;fill:rgb(0,0,0)}svg .svg-elem-11{stroke-dashoffset:100.71990203857422px;stroke-dasharray:100.71990203857422px;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 3.5s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 0.8999999999999999s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 3.5s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 0.8999999999999999s}svg.active .svg-elem-11{stroke-dashoffset:0}svg .svg-elem-12{stroke-dashoffset:43.39763641357422px;stroke-dasharray:43.39763641357422px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 3.6s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 0.99s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 3.6s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 0.99s}svg.active .svg-elem-12{stroke-dashoffset:0;fill:rgb(0,0,0)}svg .svg-elem-13{stroke-dashoffset:43.39763641357422px;stroke-dasharray:43.39763641357422px;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 3.7s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 1.08s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 3.7s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 1.08s}svg.active .svg-elem-13{stroke-dashoffset:0}svg .svg-elem-14{stroke-dashoffset:108.3414306640625px;stroke-dasharray:108.3414306640625px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 3.8s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 1.17s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 3.8s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 1.17s}svg.active .svg-elem-14{stroke-dashoffset:0;fill:rgb(0,0,0)}svg .svg-elem-15{stroke-dashoffset:108.3414306640625px;stroke-dasharray:108.3414306640625px;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 3.9000000000000004s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 1.26s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 3.9000000000000004s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 1.26s}svg.active .svg-elem-15{stroke-dashoffset:0}svg .svg-elem-16{stroke-dashoffset:75.88581085205078px;stroke-dasharray:75.88581085205078px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 4s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 1.3499999999999999s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 4s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 1.3499999999999999s}svg.active .svg-elem-16{stroke-dashoffset:0;fill:rgb(0,0,0)}svg .svg-elem-17{stroke-dashoffset:75.88581085205078px;stroke-dasharray:75.88581085205078px;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 4.1s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 1.44s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 4.1s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 1.44s}svg.active .svg-elem-17{stroke-dashoffset:0}svg .svg-elem-18{stroke-dashoffset:173.5455322265625px;stroke-dasharray:173.5455322265625px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 4.2s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 1.53s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 4.2s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 1.53s}svg.active .svg-elem-18{stroke-dashoffset:0;fill:rgb(0,179,159)}svg .svg-elem-19{stroke-dashoffset:173.5973358154297px;stroke-dasharray:173.5973358154297px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 4.3s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 1.6199999999999999s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 4.3s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 1.6199999999999999s}svg.active .svg-elem-19{stroke-dashoffset:0;fill:rgb(0,179,159)}svg .svg-elem-20{stroke-dashoffset:173.56723022460938px;stroke-dasharray:173.56723022460938px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 4.4s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 1.71s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 4.4s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 1.71s}svg.active .svg-elem-20{stroke-dashoffset:0;fill:rgb(0,179,159)}svg .svg-elem-21{stroke-dashoffset:75.43915557861328px;stroke-dasharray:75.43915557861328px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 4.5s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 1.7999999999999998s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 4.5s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 1.7999999999999998s}svg.active .svg-elem-21{stroke-dashoffset:0;fill:rgb(0,0,0)}svg .svg-elem-22{stroke-dashoffset:75.43915557861328px;stroke-dasharray:75.43915557861328px;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 4.6s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 1.89s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 4.6s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 1.89s}svg.active .svg-elem-22{stroke-dashoffset:0}svg .svg-elem-23{stroke-dashoffset:21.905780792236328px;stroke-dasharray:21.905780792236328px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 4.7s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 1.98s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 4.7s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 1.98s}svg.active .svg-elem-23{stroke-dashoffset:0;fill:rgb(0,0,0)}svg .svg-elem-24{stroke-dashoffset:21.905780792236328px;stroke-dasharray:21.905780792236328px;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 4.800000000000001s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 2.07s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 4.800000000000001s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 2.07s}svg.active .svg-elem-24{stroke-dashoffset:0}svg .svg-elem-25{stroke-dashoffset:15.808277130126953px;stroke-dasharray:15.808277130126953px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 4.9s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 2.16s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 4.9s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 2.16s}svg.active .svg-elem-25{stroke-dashoffset:0;fill:rgb(0,0,0)}svg .svg-elem-26{stroke-dashoffset:15.808277130126953px;stroke-dasharray:15.808277130126953px;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 5s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 2.25s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 5s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 2.25s}svg.active .svg-elem-26{stroke-dashoffset:0}svg .svg-elem-27{stroke-dashoffset:103.98786926269531px;stroke-dasharray:103.98786926269531px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 5.1s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 2.34s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 5.1s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 2.34s}svg.active .svg-elem-27{stroke-dashoffset:0;fill:rgb(0,0,0)}svg .svg-elem-28{stroke-dashoffset:103.98786926269531px;stroke-dasharray:103.98786926269531px;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 5.2s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 2.4299999999999997s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 5.2s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 2.4299999999999997s}svg.active .svg-elem-28{stroke-dashoffset:0}svg .svg-elem-29{stroke-dashoffset:173.5672149658203px;stroke-dasharray:173.5672149658203px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 5.300000000000001s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 2.52s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 5.300000000000001s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 2.52s}svg.active .svg-elem-29{stroke-dashoffset:0;fill:rgb(0,179,159)}svg .svg-elem-30{stroke-dashoffset:15.808284759521484px;stroke-dasharray:15.808284759521484px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 5.4s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 2.61s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 5.4s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 2.61s}svg.active .svg-elem-30{stroke-dashoffset:0;fill:rgb(0,0,0)}svg .svg-elem-31{stroke-dashoffset:15.808284759521484px;stroke-dasharray:15.808284759521484px;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 5.5s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 2.6999999999999997s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 5.5s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 2.6999999999999997s}svg.active .svg-elem-31{stroke-dashoffset:0}svg .svg-elem-32{stroke-dashoffset:75.43917846679688px;stroke-dasharray:75.43917846679688px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 5.6s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 2.79s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 5.6s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 2.79s}svg.active .svg-elem-32{stroke-dashoffset:0;fill:rgb(0,0,0)}svg .svg-elem-33{stroke-dashoffset:75.43917846679688px;stroke-dasharray:75.43917846679688px;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 5.7s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 2.88s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 5.7s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 2.88s}svg.active .svg-elem-33{stroke-dashoffset:0}svg .svg-elem-34{stroke-dashoffset:173.5671844482422px;stroke-dasharray:173.5671844482422px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 5.800000000000001s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 2.9699999999999998s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 5.800000000000001s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 2.9699999999999998s}svg.active .svg-elem-34{stroke-dashoffset:0;fill:rgb(0,179,159)}svg .svg-elem-35{stroke-dashoffset:173.567138671875px;stroke-dasharray:173.567138671875px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 5.9s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 3.06s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 5.9s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 3.06s}svg.active .svg-elem-35{stroke-dashoffset:0;fill:rgb(0,179,159)}svg .svg-elem-36{stroke-dashoffset:173.5671844482422px;stroke-dasharray:173.5671844482422px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 6s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 3.15s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 6s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 3.15s}svg.active .svg-elem-36{stroke-dashoffset:0;fill:rgb(0,179,159)}svg .svg-elem-37{stroke-dashoffset:75.42085266113281px;stroke-dasharray:75.42085266113281px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 6.1s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 3.2399999999999998s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 6.1s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 3.2399999999999998s}svg.active .svg-elem-37{stroke-dashoffset:0;fill:rgb(0,0,0)}svg .svg-elem-38{stroke-dashoffset:75.42085266113281px;stroke-dasharray:75.42085266113281px;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 6.2s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 3.33s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 6.2s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 3.33s}svg.active .svg-elem-38{stroke-dashoffset:0}svg .svg-elem-39{stroke-dashoffset:21.905784606933594px;stroke-dasharray:21.905784606933594px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 6.300000000000001s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 3.42s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 6.300000000000001s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 3.42s}svg.active .svg-elem-39{stroke-dashoffset:0;fill:rgb(0,0,0)}svg .svg-elem-40{stroke-dashoffset:21.905784606933594px;stroke-dasharray:21.905784606933594px;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 6.4s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 3.51s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 6.4s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 3.51s}svg.active .svg-elem-40{stroke-dashoffset:0}svg .svg-elem-41{stroke-dashoffset:15.808269500732422px;stroke-dasharray:15.808269500732422px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 6.5s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 3.5999999999999996s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 6.5s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 3.5999999999999996s}svg.active .svg-elem-41{stroke-dashoffset:0;fill:rgb(0,0,0)}svg .svg-elem-42{stroke-dashoffset:15.808269500732422px;stroke-dasharray:15.808269500732422px;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 6.6000000000000005s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 3.69s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 6.6000000000000005s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 3.69s}svg.active .svg-elem-42{stroke-dashoffset:0}svg .svg-elem-43{stroke-dashoffset:173.5672149658203px;stroke-dasharray:173.5672149658203px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 6.7s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 3.78s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 6.7s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 3.78s}svg.active .svg-elem-43{stroke-dashoffset:0;fill:rgb(0,179,159)}svg .svg-elem-44{stroke-dashoffset:15.808269500732422px;stroke-dasharray:15.808269500732422px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 6.8s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 3.8699999999999997s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 6.8s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 3.8699999999999997s}svg.active .svg-elem-44{stroke-dashoffset:0;fill:rgb(0,0,0)}svg .svg-elem-45{stroke-dashoffset:15.808269500732422px;stroke-dasharray:15.808269500732422px;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 6.9s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 3.96s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 6.9s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 3.96s}svg.active .svg-elem-45{stroke-dashoffset:0}svg .svg-elem-46{stroke-dashoffset:75.43917846679688px;stroke-dasharray:75.43917846679688px;fill:transparent;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 7s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 4.05s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 7s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 4.05s}svg.active .svg-elem-46{stroke-dashoffset:0;fill:rgb(0,0,0)}svg .svg-elem-47{stroke-dashoffset:75.43917846679688px;stroke-dasharray:75.43917846679688px;-webkit-transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 7.1000000000000005s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 4.14s;transition:stroke-dashoffset 0.9s cubic-bezier(0.6,-0.28,0.735,0.045) 7.1000000000000005s,fill 0.7s cubic-bezier(0.6,0.04,0.98,0.335) 4.14s}svg.active .svg-elem-47{stroke-dashoffset:0}
}
  
`;
export default MeshSectionWrapper;
