export const meet_links_data = [
  {
    day : "Mondays",
    meeting : "Layer5 Websites Meeting",
    slack_channel : "#websites",
    slack_link : "https://layer5io.slack.com/archives/C015QJKUMPU",
    meeting_minutes : "https://bit.ly/2XK4eQV",
    meeting_link : "https://meet.layer5.io/websites",
    meeting_recordings : "https://www.youtube.com/watch?v=Zba0b0ZojOI&list=PL3A-A6hPO2IO1ZuLj3cbOTdi-hlkF4Lqu",
  },
  {
    day : "Mondays",
    meeting : "WebAssembly Filters Meeting",
    slack_channel : "#wasm",
    slack_link : "https://layer5io.slack.com/archives/C012UMS2MCM",
    meeting_minutes : "https://bit.ly/3zGZgGg",
    meeting_link : "https://meet.layer5.io/wasm",
    meeting_recordings : "https://www.youtube.com/playlist?list=PL3A-A6hPO2IOur7idhSAUf6hySLn-hdVD",
  },
  {
    day : "Tuesdays",
    meeting : "Meshery MeshSync/MeshMap Meeting",
    slack_channel : "#meshery-ci",
    slack_link : "https://layer5io.slack.com/archives/C010LFFGFFA",
    meeting_minutes : "https://bit.ly/3aXOaAs",
    meeting_link : "https://meet.layer5.io/meshmap",
    meeting_recordings : "https://www.youtube.com/playlist?list=PL3A-A6hPO2IMPPqVjuzgqNU5xwnFFn3n0",
  },
  {
    day : "Wednesdays",
    meeting : "Meshery Development Meeting",
    slack_channel : "#meshery",
    slack_link : "https://layer5io.slack.com/archives/CFGG6U10E",
    meeting_minutes : "https://bit.ly/31OGQTk",
    meeting_link : "https://meet.layer5.io/meshery",
    meeting_recordings : "https://www.youtube.com/playlist?list=PL3A-A6hPO2IMPPqVjuzgqNU5xwnFFn3n0",
  },
  {
    day : "2nd & 4th Thursday",
    meeting : "Meshery CI Meeting",
    slack_channel : "#meshery-ci",
    slack_link : "https://layer5io.slack.com/archives/C011VPREG2Z",
    meeting_minutes : "https://docs.google.com/document/d/1GrVdGHZAYeu6wHNLLoiaKNqBtk7enXE9XeDRCvdA4bY/edit",
    meeting_link : "https://meet.layer5.io/meshery-ci",
    meeting_recordings : "https://www.youtube.com/playlist?list=PL3A-A6hPO2IM7rYiKxG4l3eQNc6X3IUex",
  },
  {
    day : "Thursdays",
    meeting : "Layer5 Newcomers' Meeting",
    slack_channel : "#newcomers",
    slack_link : "https://layer5io.slack.com/archives/C019426UBNY",
    meeting_minutes : "https://docs.google.com/document/d/1aHarIyIL__HRq_4klYOUsEXP5SQLlmb50W17yKdNmpU/edit#",
    meeting_link : "https://meet.layer5.io/newcomers",
    meeting_recordings : "https://www.youtube.com/playlist?list=PL3A-A6hPO2IMPPqVjuzgqNU5xwnFFn3n0",
  },
  {
    day : "Fridays",
    meeting : "Layer5 Community Meeting",
    slack_channel : "#general",
    slack_link : "https://layer5io.slack.com/archives/CDM0ACDM5",
    meeting_minutes : "https://bit.ly/2It7IA4",
    meeting_link : "https://meet.layer5.io/community",
    meeting_recordings : "https://www.youtube.com/playlist?list=PL3A-A6hPO2IMPPqVjuzgqNU5xwnFFn3n0",
  },
  {
    day : "Biweekly Thursday",
    meeting : "Service Mesh Performance Meeting",
    slack_channel : "#performance",
    slack_link : "https://layer5io.slack.com/archives/CVBGPTFJN",
    meeting_minutes : "https://bit.ly/3B7uIy9",
    meeting_link : "https://meet.layer5.io/smp",
    meeting_recordings : "https://www.youtube.com/playlist?list=PL3A-A6hPO2IPZ3dP6FgZBAA0dZFmmX0kA",
  },
  {
    day : "Biweekly Wednesday",
    meeting : "CNCF SMI Community Meeting",
    slack_channel : "#smi",
    slack_link : "https://layer5io.slack.com/archives/CDM0ACDM5",
    meeting_minutes : "https://docs.google.com/document/d/1NTBaJf6LhUBlF8_lfvBBt_MbyPvT-6CZNg6Ckpm_yCo/edit",
    meeting_link : "https://zoom.us/my/cncfsmiproject",
    meeting_recordings : "https://www.youtube.com/playlist?list=PL3A-A6hPO2IMPPqVjuzgqNU5xwnFFn3n0",
  },
  {
    day : "1st & 3rd Thursday",
    meeting : "CNCF TAG Network Meeting",
    slack_channel : "#tag-network",
    slack_link : "",
    meeting_minutes : "https://docs.google.com/document/d/18hYemFKK_PC_KbT_TDBUgb0rknOuIhikkRxer4_bv4Q/edit#",
    meeting_link : "https://zoom.us/my/cncftagnetwork",
    meeting_recordings : "https://www.youtube.com/playlist?list=PL3A-A6hPO2IMPPqVjuzgqNU5xwnFFn3n0",
  },
];
