export const meet_links_data= [
    {
        meeting: "Layer5 Community Meeting",
        slack_channel: "#general",
        slack_link: "https://layer5io.slack.com/archives/CDM0ACDM5",
        meeting_minutes: "https://bit.ly/2It7IA4",
        meeting_link: "https://meet.layer5.io/community",
        meeting_recordings: "https://www.youtube.com/playlist?list=PL3A-A6hPO2IMPPqVjuzgqNU5xwnFFn3n0",
    },
    {
        meeting: "Websites Meeting",
        slack_channel: "#websites",
        slack_link: "https://layer5io.slack.com/archives/C015QJKUMPU",
        meeting_minutes: "https://bit.ly/2XK4eQV",
        meeting_link: "https://meet.layer5.io/websites",
        meeting_recordings: "https://www.youtube.com/watch?v=Zba0b0ZojOI&list=PL3A-A6hPO2IO1ZuLj3cbOTdi-hlkF4Lqu",
    },
    {
        meeting: "Meshery Development Meeting",
        slack_channel: "#meshery",
        slack_link: "https://layer5io.slack.com/archives/CDM0ACDM5",
        meeting_minutes: "https://bit.ly/2It7IA4",
        meeting_link: "https://meet.layer5.io/community",
        meeting_recordings: "https://www.youtube.com/playlist?list=PL3A-A6hPO2IMPPqVjuzgqNU5xwnFFn3n0",
    },
    {
        meeting: "MeshMap Meeting",
        slack_channel: "#meshery-ci",
        slack_link: "https://layer5io.slack.com/archives/CDM0ACDM5",
        meeting_minutes: "https://bit.ly/2It7IA4",
        meeting_link: "https://meet.layer5.io/community",
        meeting_recordings: "https://www.youtube.com/playlist?list=PL3A-A6hPO2IMPPqVjuzgqNU5xwnFFn3n0",
    },
    {
        meeting: "Newcomers' Meeting",
        slack_channel: "#newcomers",
        slack_link: "https://layer5io.slack.com/archives/CDM0ACDM5",
        meeting_minutes: "https://bit.ly/2It7IA4",
        meeting_link: "https://meet.layer5.io/community",
        meeting_recordings: "https://www.youtube.com/playlist?list=PL3A-A6hPO2IMPPqVjuzgqNU5xwnFFn3n0",
    },
    {
        meeting: "CNCF - SMI Community Meeting",
        slack_channel: "#smi",
        slack_link: "https://layer5io.slack.com/archives/CDM0ACDM5",
        meeting_minutes: "https://bit.ly/2It7IA4",
        meeting_link: "https://meet.layer5.io/community",
        meeting_recordings: "https://www.youtube.com/playlist?list=PL3A-A6hPO2IMPPqVjuzgqNU5xwnFFn3n0",
    },
    {
        meeting: "CNCF - SIG Network Meeting",
        slack_channel: "#sig-network",
        slack_link: "https://layer5io.slack.com/archives/CDM0ACDM5",
        meeting_minutes: "https://bit.ly/2It7IA4",
        meeting_link: "https://meet.layer5.io/community",
        meeting_recordings: "https://www.youtube.com/playlist?list=PL3A-A6hPO2IMPPqVjuzgqNU5xwnFFn3n0",
    },
];
