import React from "react";
import { GiCheckMark } from "@react-icons/all-files/gi/GiCheckMark";
import { MdClose } from "@react-icons/all-files/md/MdClose";
import MeshMap from "./icons/meshmap-icon.svg";
import Support from "./icons/support.svg";
import Collab from "./icons/collaboration.svg";
import Lifecycle from "./icons/lifecycle.svg";
import Identity from "./icons/identity.svg";
import Notification from "./icons/notification.svg";
import Configuration from "./icons/configuration.svg";
import Perforamance from "./icons/perf.svg";
import comingSoon from "./icons/coming-soon.webp";

export const details = [
  {
    id: 0,
    category: "Configuration Management",
    icon: Configuration,
    features: [
      {
        feature: "Cloud Native Designs",
        description: "Import and export your designs using your local filesystem or remote URL.",
        free: <GiCheckMark className="yes-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Configurable OAuth callbacks",
        description: "Customize OAuth callback URLs to seamlessly integrate authentication workflows into your application.",
        free: <GiCheckMark className="yes-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "WASM Envoy Filter Management",
        description: "Efficient WASM Envoy Filter Management in Meshery UI and CLI",
        free: <MdClose className="no-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Cloud Native Patterns",
        description: "Combine designs into well-curated, reusable patterns imbued with your customized best practices.",
        free: <MdClose className="no-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Design Dry-run",
        description: "Test and verify configuration changes in a separate environment.",
        free: <MdClose className="no-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Version your infrastructure configuration designs",
        description: "Effortlessly version your infrastructure configuration designs. Keep track of changes, maintain consistency, and enhance collaboration across your team.",
        free: <MdClose className="no-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Custom Kubernetes clusters configuration",
        description: "Apply custom configuration to your Kubernetes clusters",
        free: <MdClose className="no-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
    ],
  },
  {
    id: 2,
    category: "Lifecycle Management",
    icon: Lifecycle,
    features: [
      {
        feature: "Configure and deploy any cloud native infrastructure",
        description: "230+ Built-In integrations, support Cloud Native Infrastructure and Apps",
        free: <GiCheckMark className="yes-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Cluster discovery",
        description: "Day 2 support for ongoing synchronization of Kubernetes configuration, workloads and cloud native changes.",
        free: <GiCheckMark className="yes-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Multiple Kubernetes Clusters",
        description: "Ongoing synchronization of Kubernetes configuration, workloads and cloud native changes across any number of Kubernetes clusters.",
        free: <GiCheckMark className="yes-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Helm Chart Generation",
        description: "Real-Time Helm Chart Generation for CLI and UI",
        free: <GiCheckMark className="yes-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Support for Streamlined Environments",
        description: "Unlock streamlined environments with enhanced multi-cluster support. Seamlessly manage multiple clusters to optimize efficiency and streamline operations.",
        free: <MdClose className="no-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
    ],
  },
  {
    id: 3,
    category: "MeshMap",
    icon: MeshMap,
    features: [
      {
        feature: "Service Performance",
        description: "Continuous visibility across all of your clusters and workloads.",
        free: <GiCheckMark className="yes-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Application Import",
        description: "Import your existing Kubernetes, Helm, or Docker Compose applications.",
        free: <GiCheckMark className="yes-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Visual Design",
        description: "Drag-n-drop cloud native infrastructure designer to configure, model, and deploy your workloads",
        free: <MdClose className="no-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Timeline (DVR)",
        description: "Playback service transactions. Scrub over the history of changes to your deployments. ",
        free: <MdClose className="no-icon" />,
        team: <MdClose className="no-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
    ],
  },
  {
    id: 4,
    category: "Performance Management",
    icon: Perforamance,
    features: [
      {
        feature: "Parallel Load Generation",
        description: "Single Load Generator: Support testing multiple endpoints simultaneously.",
        free: <GiCheckMark className="yes-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Performance Profiles",
        description: "Create and share performance profiles and test results with team members.",
        free: <GiCheckMark className="yes-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "MeshMark",
        description: "Identify the cost of a specific network function.",
        free: <GiCheckMark className="yes-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Test user flow performance",
        description: "Efficiently evaluate and optimize user flow performance with our testing capabilities.",
        free: <MdClose className="no-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Distributed Load Generation",
        description: "Distributed Load Generator: Support multiple Meshery clients generating load, collecting and coalescing results into a single report.",
        free: <MdClose className="no-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "GitOps - Cloud Native Performance GitHub Action",
        description: "Integrate performance analysis as a gate in your GitOps pipeline, using performance profiles to run repeatable tests and avoid regression issues before they start. Configure this action to trigger with each of your releases, on every pull request. or any GitHub workflow trigger event.",
        free: <MdClose className="no-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Track your workload performance",
        description: "Efficiently monitor and optimize workload performance. Gain insights into your system's efficiency and make informed decisions to enhance productivity.",
        free: <MdClose className="no-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      // {
      //   feature: "Service Mesh Interface Conformance GitHub Action",
      //   description: "Using Meshery as the offical SMI Conformance validation tool, configure this action to trigger with each of your releases, on every pull request. or any GitHub workflow trigger event.",
      //   free: <MdClose className="no-icon" />,
      //   team: <GiCheckMark className="yes-icon" />,
      //   enterprise: <GiCheckMark className="yes-icon" />,
      // },
      {
        feature: "Certificate support in performance profiles",
        description: "Enable certificate support within performance profiles. Enhance security and performance by seamlessly integrating certificates into your profiles.",
        free: <MdClose className="no-icon" />,
        team: <MdClose className="no-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
    ],
  },
  {
    id: 1,
    category: "Collaboration",
    icon: Collab,
    features: [
      {
        feature: "Multiplayer designer for kubernetes and cloud",
        description: "Collaborate in real-time on Kubernetes and cloud configurations for streamlined teamwork and enhanced productivity.",
        free: <GiCheckMark className="yes-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Collaborators for public designs",
        description: "Invite any Layer5 Cloud user, or all Meshery users, to work with you on a public design that you control – including making changes and releasing new versions.",
        free: <MdClose className="no-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Design Reviews",
        description: "Discuss any design by leaving review comments or notes on a specific design. Control who has access, notify discussion participants with updates, and link from anywhere.",
        free: <MdClose className="no-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Team Chat",
        description: "Message in real-time, unattached to a specific design. Control who can participate in the discussion.",
        free: <MdClose className="no-icon" />,
        team: <MdClose className="no-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Organization and Team Management",
        description: "Manage access to designs on a team-by-team, or individual user, basis.",
        free: <MdClose className="no-icon" />,
        team: <MdClose className="no-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Collaborative Design",
        description: "Create and collaborate in online designs in real-time.",
        free: <MdClose className="no-icon" />,
        team: <MdClose className="no-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Add-ons",
        description: "Access a variety of third-party applications, right from MeshMap. Send a message to Slack, identify an on-duty team to page, or raise an alarm in Layer5 Cloud.",
        free: <MdClose className="no-icon" />,
        team: <MdClose className="no-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
    ],
  },
  {
    id: 5,
    category: "Identity & Access Management",
    icon: Identity,
    features: [
      {
        feature: "Single User",
        description: "Implicit user; implicit role (admin)",
        free: <GiCheckMark className="yes-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Multiple Users",
        description: "Multi-tenancy",
        free: <GiCheckMark className="yes-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Individual User",
        description: "Preferences	Allows preferences to be set per user.",
        free: <GiCheckMark className="yes-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Built-in Roles",
        description: "Static - out of the box",
        free: <MdClose className="no-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "User-defined Roles",
        description: "Customizable roles for specific permission assignments",
        free: <MdClose className="no-icon" />,
        team: <MdClose className="no-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Authentication: LDAP",
        description: "Access Meshery using your existing accounts and centrally manage repository access.",
        free: <MdClose className="no-icon" />,
        team: <MdClose className="no-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Authentication: SAML",
        description: "Use an identity provider to manage the identities Meshery users and applications.",
        free: <MdClose className="no-icon" />,
        team: <MdClose className="no-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Authorization",
        description: "Own and control the user accounts of your enterprise members through your identity provider (IdP).",
        free: <MdClose className="no-icon" />,
        team: <MdClose className="no-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
    ],
  },
  {
    id: 6,
    category: "Incident Management",
    icon: Notification,
    features: [
      {
        feature: "Notification Center",
        description: "Events: Reporting of Meshery provisioning aand managagement events.",
        free: <GiCheckMark className="yes-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Audit Trail",
        description: "Detailed accounting of user activity. Historical record or each action taken.",
        free: <GiCheckMark className="yes-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Alert Generation",
        description: "Dismiss individual; Dismiss bulk.",
        free: <GiCheckMark className="yes-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Event Correlation",
        description: "Policy-based",
        free: <MdClose className="no-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Traffic Replay",
        description: "Visual event replay in MeshMap",
        free: <MdClose className="no-icon" />,
        team: <MdClose className="no-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
    ],
  },
  {
    id: 7,
    category: "Support and Deployment",
    icon: Support,
    features: [
      {
        feature: "Community Support",
        description: "Get help with most of your Meshery questions and issues in our community discussion forum.",
        free: <GiCheckMark className="yes-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Standard Support",
        description: "Layer5 Support can help you troubleshoot issues you run into while using Meshery. Get support via the web.",
        free: <MdClose className="no-icon" />,
        team: <GiCheckMark className="yes-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Premium and Premium Plus Support",
        description: "With Premium, get a 30-minute SLA and 24/7 web and phone support. With Premium Plus, get everything in Premium plus your own Support Account Manager and more.",
        free: <MdClose className="no-icon" />,
        team: <MdClose className="no-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Self-hosted Deployment",
        description: "Self-hosted Layer5 Cloud for on-prem appliances or self-managed cloud tenants.",
        free: <MdClose className="no-icon" />,
        team: <MdClose className="no-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Phone Support",
        description: "Layer5 Support can help you troubleshoot issues you run into while using Meshery. Get support via phone.",
        free: <MdClose className="no-icon" />,
        team: <MdClose className="no-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
      {
        feature: "Invoice Billing",
        description: "Pay bills via invoice, rather than using your credit card.",
        free: <MdClose className="no-icon" />,
        team: <MdClose className="no-icon" />,
        enterprise: <GiCheckMark className="yes-icon" />,
      },
    ],
  },
];

export const options = [
  {
    tier: "Personal",
    featured: true,
    monthlyprice: 0,
    yearlyprice: 0,
    byline: "Open Source features, plus:",
    button: ["Join for Free", "https://meshery.layer5.io"],
    summary: [
      { id: 0, category: "Cloud Native Design Patterns", description: "Import and export your designs using your local filesystem or remote URL." },
      { id: 1, category: "Multiple Kubernetes Clusters", description: "Ongoing synchronization of Kubernetes configuration, workloads and cloud native infrastructure changes across any number of Kubernetes clusters." },
      { id: 2, category: "Cluster Discovery", description: "Day 2 support for ongoing synchronization of Kubernetes configuration, workloads and cloud native infrastructure changes." },
      { id: 3, category: "Microservices Performance", description: "Continuous visibility across all of your clusters and workloads." },
      { id: 4, category: "Load Generation", description: "Single Load Generator: Support testing multiple endpoints simultaneously. Distributed Load Generator: Support multiple Meshery clients generating load, collecting and coalescing results into a single report." },
      { id: 5, category: "Open Policy Agent integration", description: "Ensure adherence to performance budgets with comprehensive support in Patterns. Safeguard service requests through JWT-based authorization. Enforce admission control for specific workloads, empowering seamless governance across your infrastructure." },
      { id: 6, category: "Continuous Service Monitoring", description: "Experience uninterrupted oversight of your service quality with our Continuous Quality of Service Monitoring." },
      { id: 7, category: "Audit Trail", description: "Log of all actions invoked by users." },
      { id: 8, category: "Alert Generation", description: "Dismiss individual; Dismiss bulk." },
      { id: 9, category: "mesheryctl commands", description: " Seamlessly manage your configurations, deployments, and interactions through our intuitive and powerful command-line interface." },
      { id: 10, category: "MeshMark", description: "Identify the cost of a specific network function." },
      { id: 11, category: "Notification Center", description: "Consolidate all important updates, alerts, and messages in one centralized hub, ensuring you never miss a critical communication or task." },
      { id: 12, category: "Screenshots", description: "Capture and share visual snapshots of your work with ease using our Screenshots feature." },
      { id: 13, category: "Community Support", description: "Get help with most of your Meshery questions and issues in our Community Forum." },
    ]
  },
  {
    tier: "Team",
    featured: false,
    monthlyprice: 9.99,
    yearlyprice: 100,
    byline: "Everything in Free, plus:",
    button: ["Contact Sales", "https://us15.list-manage.com/contact-form?u=6b50be5aea3dfe1fd4c041d80&form_id=d0ffe17c92d8014ede6b721aa16096e8"],
    summary: [
      { id: 0, category: "Dry-run", description: "Test and verify configuration changes in a separate environment." },
      { id: 1, category: "Design Reviews", description: "Discuss any design by leaving review comments or notes on a specific design. Control who has access, notify discussion participants with updates, and link from anywhere." },
      { id: 2, category: "WASM Envoy Filter Management", description: "Efficient WASM Envoy Filter Management in Meshery UI and CL" },
      { id: 3, category: "Visual Design", description: "Drag-n-drop cloud native infrastructure designer to configure, model, and deploy your workloads." },
      { id: 4, category: "Design versioning", description: "Connect your favorite git provider and version your designs." },
      { id: 5, category: "Distributed Performance Analysis", description: "Automatically suggest timeout or retry settings for a given service." },
      { id: 6, category: "Performance Profiles", description: "Share performance profiles and test results with individual users or teams." },
      { id: 7, category: "Test user flow performance", description: "Efficiently evaluate and optimize user flow performance with our testing capabilities." },
      { id: 8, category: "Built-in Roles", description: "Static - out of the box" },
      { id: 9, category: "Comparative Testing", description: "Detect real-time anomalies and Historical views: Infrastructure-centric." },
      { id: 10, category: "Calendaring", description: "Get integration with GSuite and integration with Microsoft Outlook." },
      { id: 11, category: "Standard Support", description: "Layer5 Support can help you troubleshoot issues you run into while using Meshery. Get support via the web." },
      { id: 12, category: "Add-ons", description: "Access a variety of third-party applications, right from MeshMap. Send a message to Slack, identify an on-duty team to page, or raise an alarm in Datadog." },
    ]
  },
  {
    tier: "Enterprise",
    featured: false,
    monthlyprice: 15.99,
    yearlyprice: 180,
    pricing_coming_soon: <img src={comingSoon}></img>,
    byline: "Everything in Team, plus:",
    button: ["Coming Soon", ""],
    summary: [
      { id: 0, category: "User-defined Roles", description: "Customizable roles for specific permission assignments" },
      { id: 1, category: "Authentication: LDAP", description: "Access Meshery  using your existing accounts and centrally manage repository access." },
      { id: 2, category: "Authentication: SAML", description: "Use an identity provider to manage the identities of Meshery users and applications." },
      { id: 3, category: "Self-hosted Deployment", description: "Self-hosted Layer5 Cloud for on-prem appliances or self-managed cloud tenants." },
      { id: 4, category: "Traffic Replay", description: "Visual event replay in MeshMap." },
      { id: 5, category: "Certificate support in performance profiles", description: "Enable certificate support within performance profiles. Enhance security and performance by seamlessly integrating certificates into your profiles." },
      { id: 6, category: "Phone Support", description: "Layer5 Support can help you troubleshoot issues you run into while using Meshery. Get support via phone." },
      { id: 7, category: "Organization and Team Management", description: "Manage access to designs on a team-by-team, or individual user, basis." },
      { id: 8, category: "Team Chat", description: "Message in real-time, unattached to a specific design. Control who can pariticpate in the discussion." },
      { id: 9, category: "Serverless Pricing", description: "Subscription plan management. Transformation of workflow pricing model." },
      { id: 10, category: "Premium and Premium Plus Support", description: "With Premium, get a 30-minute SLA and 24/7 web and phone support. With Premium Plus, get everything in Premium plus your own Support Account Manager and more." },
      { id: 11, category: "Phone Support", description: "Layer5 Support can help you troubleshoot issues you run into while using Meshery. Get support via phone." },
    ]
  },
];
