name: Deploy Gatsby site to Pages

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages-deployment"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 #v7.0.0
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Build Gatsby site
        run: |
          npm run build
          echo "layer5.io" > public/CNAME
          touch public/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f #v4.8.0
        with:
          folder: ./public
          branch: gh-pages
          clean: true
          clean-exclude: |
            pr-preview
            .well-known
          force: false