name: Label PRs

on:
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: srvaroa/labeler@v0.3
        env:
          GITHUB_TOKEN: "${{ secrets.GH_ACCESS_TOKEN }}"
